{
 "title": "Internet maison",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Lease expire time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_expires / 60 / 60", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_information{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN IP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_information{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN GW",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_information{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_information{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "active_device", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{job=\"asus\"} / 60 / 60 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(memory_free / memory_total) *100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu1_percent{job=\"asus\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu2_percent{job=\"asus\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu3_percent{job=\"asus\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "cpu4_percent{job=\"asus\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}